#!/bin/bash
# 10 8 * * *  cd /tmp/ && git clone https://github.com/hale777/crypto.git && cd crypto && chmod +x crypto.sh && ./crypto.sh
cd /tmp/
git clone https://github.com/hale777/crypto.git
cd crypto
chmod +x crypto.sh
sh crypto.sh
